function cond_source() {
  if [ -f $1 ]; then
    . $1
  fi
}

source $HOME/.conf/bash/variables.bash
cond_source $CONF_HOME/bash/local/variables.bash

# If running interactively
if [[ $- =~ i ]]; then
  # commands
  source $CONF_HOME/bash/commands.bash
  cond_source $CONF_HOME/bash/local/commands.bash

  # completion
  for file in $CONF_HOME/bash/completion/*; do
  	source $file
  done

  # shell behavior
  source $CONF_HOME/bash/shell.bash
  cond_source $CONF_HOME/bash/local/shell.bash

  # prompt
  source $CONF_HOME/bash/prompt.bash
  cond_source $CONF_HOME/bash/local/prompt.bash
fi
